//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uno
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entradas
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Tipo { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
